[package]
name = "setreuid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cvt = "0.1.1"
libc = "0.2.137"

[[bin]]
name = "setreuid"
path = "setreuid.rs"
